### ISSUE TITLE
Support unbuffered, unmangled access to remote stdout/stderror from `run()`

### ISSUE THREAD

**Issue by mjog** [fabric/fabric#1066]
It isn't possible to get access to the remote process's stdout/stderr from `run()`, without it being mangled for display to humans and/or buffered.

This makes it impossible/infeasible to capture formatted, binary and/or large amounts of data from a process's output streams directly. Instead, the output needs to be redirected to a securely created temp file, which is then `get()`'ed, then deleted. This is a lot of work for something that should be doable just by specifying `run(..., stdout=open("huge.jpg"))`.

The following are currently non-solutions:
- Setting `output["stdout"] = False` and/or `output["stderr"] = False` does not work, since that also stops the `stdout`/`stderr` args to passed to `run()` being written to.
- Setting `env.output_prefix = False` does not work since the output is still buffered internally and the data sent to the `stdout`/`stderr` args to passed to `run()` is still mangled for display.

IMHO, the correct thing would be to fix both: Ensure that even if with `output["stdout"] = False` and/or `output["stderr"] = False`, the data from those streams is neither buffered or printed, but any file-like objects passed as the `stdout`/`stderr` args to passed to `run()` are still written to (if you don't want that to happen, don't pass them as args!). Then, ensure the data written `stdout`/`stderr` args is always written unmangled, i.e. as-is received from the stream. Anyone who for some reason still want the mangled data can get it from the `run()`'s return value.

**Comment by bitprophet** [comment]
This is implemented in 2.0 via Invoke-level functionality in at least two ways:

- Can replace the default out/err streams with explicit `out_stream`/`err_stream` args to `run`, so e.g. hand in your own file-like objects which do whatever you want. I.e. basically the same as was suggested by the OP.
- There's also a 'watchers' feature which allows user-defined function/methods that are handed the current contents of the read buffer (again, on a per stream basis) on each stream read()/recv(), and have the option (not requirement) of yielding stdin to be written in response.

In both cases there is zero manipulation performed on the stream data before user code gets its hands on it, with the possible exception of decoding from bytes to Unicode (and even this is likely to change due to #438, meaning you'd also gain access to the 100% raw un-decoded bytes.)
