### ISSUE TITLE
prompt_for_password makes fabric stall

### ISSUE THREAD

**Issue by jonaslejon** [fabric/fabric#1102]
When prompt_for_password() is called for some kinda reason and no console is available everything will stall.

Is it somehow possible to set a timeout at 120 sec or detect when no console is available?

**Comment by bitprophet** [comment]
@jonaslejon Typically in this case, users will be aware of the fact they're running headless and give the `--abort-on-prompts` flag so things at least error out instead of hanging. I don't think a timeout is the right way to handle this.

Please reopen if `--abort-on-prompts` doesn't do the trick for you.
