### ISSUE TITLE
fabric.api.run() strips leading and trailing spaces of stdout

### ISSUE THREAD

**Issue by benoitbryon** [fabric/fabric#1296]
Let's consider a sh command which produces output with leading and trailing spaces. In some cases (my use case), these trailing or leading spaces matter. So, when I call `run()`, I want the result's `stdout` to include these spaces.
But it looks like `run()` strips spaces of stdout, so I don't get the exact result I expect.

As an example, when I run `echo 'hello'` in shell, I get a trailing newline, i.e. `hello\n`. So I was expecting `fabric.api.run('hello')` to produce exactly the same output, i.e. `hello\n`... But I got `hello` without the trailing newline.

Is this behaviour a feature of fabric?

* if yes, is there a way to get the result I want, i.e. with leading and trailing spaces? I couldn't figure it from the docs :(
* else, isn't it a bug?

As far as I understood, this code is involved: https://github.com/fabric/fabric/blob/1.10.1/fabric/operations.py#L831

If you like to reproduce the behaviour, check the following fabfile, where assertions fail:

```python
import fabric.api


fabric.api.env.hosts = ['localhost']


@fabric.api.task
def compare_echo():
    result_no_trailing = fabric.api.run('echo -n "Hello world"')
    result_trailing = fabric.api.run('echo "Hello world"')
    assert result_no_trailing.stdout != result_trailing.stdout


@fabric.api.task
def result_with_spaces():
    result = fabric.api.run('echo -en "\ttab-separated\tCSV\n1\t2\t3\n4\t\t"')
    assert result.stdout.endswith('\t\t')
```

Seen with versions: Fabric 1.10.1 and Python 2.7.6.

**Comment by bitprophet** [comment]
I had zero recollection of why this behavior exists, and as with a lot of such things, turns out it's because it dates from prehistory. Specifically b5b45f2470d1a868ead94a31675ae26ba9094572 (this is back when I didn't even technically run the project!)

Sadly that commit message does not specify why the strip() was added, I can only guess it was some attempt at being "clean" or dealing with some common use case where trailing whitespace existed but wasn't useful.

It's been the standard behavior for so long so we can't change it in 1.x (we could potentially add an option for it, but the API is already super top heavy...), but 2.x is around the corner and I can't imagine we'll be keeping this particular quirk around.

For example, the local command running portion of what Fabric 2 is building on (meaning: this code I am linking to is likely to become refactored & used in part for SSH execution as well) doesn't `strip`: https://github.com/pyinvoke/invoke/blob/62ca606f5b9a2f855100dbd2c9a48546335d8dad/invoke/runner.py#L231

Thanks for challenging the status quo :)

**Comment by benoitbryon** [comment]
Thanks for the reply!
A workaround solved the issue for my use case: https://github.com/benoitbryon/xal/blob/4d3e74d9e57662b529b2d2608c1b6cfce684dae5/xal/sh/fabric.py#L19-L35 ... quite a hack, but it is enough for me at the moment.
