### ISSUE TITLE
JobQueue example is outdated

### ISSUE THREAD

**Issue by dioh** [fabric/fabric#1305]
In the documentation of JobQueue
http://pydoc.net/Python/Fabric/1.4.0/fabric.job_queue/

The example shows a one parameter constructor while actually its a two parameter method.

**Comment by zerok** [comment]
You are right. Once changed there is also the issue that the sample with threading as parallelisation method doesn't work because threads don't have an exitcode.

I am completely new to the internals of fabric but shouldn't a try/catch block within the WrappedCallableTask (or Task for that matter) class solve this so that we get an exit code depending on if an exception was thrown during the task execution or not?

Or is threading at this point not really a use-case anymore?

Additionally, would it make sense to move this whole sample code into a bunch of unittests?

**Comment by sivy** [comment]
The example is still wrong in [1.9.2](http://pydoc.net/Python/Fabric/1.9.2/fabric.job_queue/).

```python
# Make a job_queue with a bubble of len 5, and have it print verbosely
jobs = JobQueue(5)
jobs._debug = True
```
