### ISSUE TITLE
Why do I need to escape equals sign when provided as part of a string in a task parameter?

### ISSUE THREAD

**Issue by carn1x** [fabric/fabric#1306]
For instance I have the following Fabric command which should be fairly obvious:

```
$ fab pip:"install django-nose==1.3"
```

To which I get the following:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fabric/main.py", line 700, in main
    commands_to_run = parse_arguments(arguments)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fabric/main.py", line 536, in parse_arguments
    k, v = result
ValueError: too many values to unpack
```

However if I escape the `==` then it runs fine, such as:

```
$ fab pip:"install django-nose\=\=1.3 --upgrade"
...
Successfully installed django-nose-1.3
```

Ultimately I'd like to write a decorate for this, but has this already been considered?

**Comment by offbyone** [comment]
The issue is that the '=' sign is an indicator of a keyword argument -- fabric command arguments support both positional, which you're trying to use, and named arguments:

fab command:"posarg"
fab command:"kwarg=value"

Detecting '==' in there is possible, but I suspect that it's probably not worth trying to enumerate the exceptions to the '=' rule; there's already a mechanism to escape them. It might be valuable to improve the error messaging there, though.

**Comment by ushuz** [comment]
Isn't double-quote enough? I think arguments parsing process should leave what's between double-quote untouched, instead of seeking keyword arguments inside it. 

```bash
fab task:arg1="val1",arg2="key=value",arg3="val3"
```

Code above will also fails because there is a `=` in `arg2`. It's really confusing as `arg2` has already been given.

**Comment by bitprophet** [comment]
@ushuz Double quoting is only a shell construct; once the program in question sees the arguments, they're gone/invisible.
