### ISSUE TITLE
Pressing enter while running can expose sudo password

### ISSUE THREAD

**Issue by mcclurem** [fabric/fabric#1339]
While running a series of commands, if you happen to press enter when a sudo prompt comes up and there's already a password in memory, it can expose it in plaintext . In addition, it appears that sometimes you can corrupt the sequence of operations that occur.

Is the local keyboard/stdin always being sent to the host along with the sequence of running commands? If so that would seem to be errant behavior. If not, and the problem is strictly accidental local echoing, could showing the output line:
`[10.0.0.23] out: sudo password:`
be hidden unless the password needs to be re-entered?

**Comment by ppkt** [comment]
I can confirm this behavior (sudo password is incorrect in this case and provided by `env.password`):
```
[192.168.0.33] sudo: whoami
[192.168.0.33] out:  < here [Enter] was pressed
[192.168.0.33] out: sudo password:
[192.168.0.33] out: mysecretpassword
[192.168.0.33] out: Niestety, proszę spróbować ponownie. < "Sorry, try again." in Polish
[192.168.0.33] out: sudo password:
[192.168.0.33] out: mysecretpassword
[192.168.0.33] out: Niestety, proszę spróbować ponownie.
[192.168.0.33] out: sudo password:
[192.168.0.33] out: mysecretpassword
[192.168.0.33] out: Niestety, proszę spróbować ponownie.
[192.168.0.33] out: sudo: 3 błędne próby wprowadzenia hasła
[192.168.0.33] out: 
```
This is pl_PL.UTF-8 locale on remote machine, but when I changed locale to en_GB.UTF-8, the problem is not present:
```
[192.168.0.33] sudo: whoami
[192.168.0.33] out: sudo password:
[192.168.0.33] out: 
[192.168.0.33] out: Sorry, try again.
[192.168.0.33] out: sudo password:
[192.168.0.33] out:  
```
And execution is hanging, waiting for password input (it's hidden, as it should be). Setting `env.again_prompt` to `u'Niestety, proszę spróbować ponownie.'` doesn't solve this problem.

**Comment by bitprophet** [comment]
Not sure why I never answered @mcclurem's question...yes, user stdin is always submitted "live" to the remote end. Can't speak directly to the greater issue here but I suspect it won't be cleanly solved until we revisit this feature set in 2.x (underway). I'll try keeping an eye on this as that gets (re)implemented.

**Comment by bitprophet** [comment]
Having mostly finished the work alluded to above, I can confirm that Fabric 1.x has a thread sitting around always throwing local stdin into remote stdin; this is required in order to have programmatic access to that remote stdin stream.

The reimplementation of this in Invoke/Fab2 does the same thing (for the same reason - even locally, if you want to write to a subprocess' stdin, you must "own" it instead of just plugging it into your own stdin - and thus you must pass it through for interactivity to work at all). Don't know yet if it exhibits the same buggy behavior - I will test.

**Comment by bitprophet** [comment]
I can't seem to reproduce this locally under Fabric 2.x. Conceptually, it may still be lurking somewhere, but needs more data on how to reproduce / confirmation from users that it's still even present in the 2.x line.
