### ISSUE TITLE
[docs] pip install fabric==dev doesn't work

### ISSUE THREAD

**Issue by slamora** [fabric/fabric#1345]
Although this command is on the [fabric installation instructions](http://www.fabfile.org/installing.html) it doesn't work (I guess that because PyPi only allows [PEP 440](https://www.python.org/dev/peps/pep-0440/) version names since a while).

    $ pip install fabric==dev
    Downloading/unpacking fabric==dev
      Could not find a version that satisfies the requirement fabric==dev
      [...]
    Cleaning up...
    No distributions matching the version for fabric==dev

Devel installation instructions could be updated to something like suggested in [Django](https://docs.djangoproject.com/en/dev/topics/install/#installing-development-version):

     $ git clone git://github.com/fabric/fabric.git fabric-trunk
     $ sudo pip install -e fabric-trunk
     (If using a virtualenv you can omit sudo.)

**Comment by bitprophet** [comment]
This is likely the same issue/set of issues as https://github.com/pyinvoke/invoke/issues/220 - I checked and the "Extract urls from long_description" option is set for fabric 1.10.1, and the tarball URL is in the long_description, but the URL itself is not listed. Probably just due to the age of the release, I haven't put up a new one since late last year (ugh!).

Once I do so, ==dev should work again (though we may need to add a note about using `--allow-unverified` for newer pip versions).

**Comment by bitprophet** [comment]
I have a bunch of stuff sitting around unreleased, looks like, so I might just pop that out today.

**Comment by bitprophet** [comment]
1.10.2 just published, and now the tarball URL appears on PyPI and I can `pip install fabric==dev` on my end when I could not before. ![](http://i.somethingawful.com/forumsystem/emoticons/emot-toot.gif)

**Comment by bitprophet** [comment]
Almost forgot - thanks for the report @slamora !

**Comment by slamora** [comment]
You're welcome! Thanks for fixing it.
