### ISSUE TITLE
DeprecationWarning: With-statements now directly support multiple context managers

### ISSUE THREAD

**Issue by chrisspen** [fabric/fabric#1364]
I recently started getting this warning. How do I fix my code to get rid of it?

At first, I thought it was for code with nested with statements, like:

    with settings(warn_only=True):
        with hide('running'):
            do_stuff()

but if I change it to:

    with settings(warn_only=True), hide('running'):
        do_stuff()

I still get the error.

**Comment by bitprophet** [comment]
That's probably due to internal use of `contextlib.nested`, since it is/was used as a workaround for lack of the newer contextmanager syntax. Which Python version are you on? Guessing that warning was added in recent versions of 2.7...

There's not much we can do about it since we still support 2.5/2.6 in v1 and the modern syntax is 2.7 only IIRC.

**Comment by Julian** [comment]
Can this be reopened these days?

`contextlib.nested` is fairly broken, which was part of the motivation for the new syntax, so on newer versions it'd be nice to opportunistically use it and avoid the warning, but even if fabric still supports 2.6, https://pypi.python.org/pypi/contextlib2 backports `ExitStack`, so we'd be able to use that on 2.6.

**Comment by bitprophet** [comment]
@Julian if a PR can be put together that isn't too disruptive, I'd probably merge it.
