### ISSUE TITLE
-P (parallel) now randomly giving "Needed to prompt for a connection..."

### ISSUE THREAD

**Issue by anjos** [fabric/fabric#1400]
I apologize in advance if this is not the appropriate channel for discussions of this kind, but I think I somehow have a bug with Fabric.

Since the upgrade to paramiko 1.16.0 last week, Fabric is now giving "random" errors with

```text
Fatal error: Needed to prompt for a connection or sudo password (host: xyz), but input would be ambiguous in parallel mode
```

I tried to update Fabric to 1.10.2, but the same issues continue. Running with `--show=debug` does not seem to be enlightening. Any suggestions on how to figure out the issue here?

**Comment by anjos** [comment]
This is not related to the upgrade to paramiko. Apparently, using the hostname (and because we have a dual IPv4/IPv6) setup, confuses the setup.

**Comment by bitprophet** [comment]
That message actually means what it says, either a connection login password (or other auth failure - because of Paramiko issues we have to guess) or a sudo password prompt is being encountered. Because it's parallel execution, we can't just feed stdin to everything and assume it'll work right, so we instead bubble this up.

If you run the exact same Fabric command without `-P`, you should presumably end up seeing this prompt yourself. E.g. server w/ different-from-usual login password, misconfigured sshd, etc etc - any auth/login problem could potentially trigger this.

Server-side state changing to trigger this when it was not previously an issue, would also explain why it just started happening recently, I'd bet.

Please comment if you can dig up an actual bug (or if shuffling Fabric/Paramiko versions around shows that it really only happens in some versions) and we can reopen. Thanks!

**Comment by anjos** [comment]
Howdy,

What you suggested does **not** apply: starting without the `-P` flag works like a charm. The issue only happens if:

1. The machine can be contacted both via IPv4 and 6
2. We use a hostname instead of the IPv4 address to access them through fabric

Would you have a test bed to check for this? Otherwise, I can provide more information on demand to try to figure this out.

**Comment by anjos** [comment]
This is valid for Fabric 1.10.x and Paramiko 1.15.x and 1.16.0.

**Comment by bitprophet** [comment]
I'd scan the Paramiko and Fabric changelogs for "IPv6" and use that as a guide for some additional version testing, I know we updated the connection logic 1 or 2 times in the last year or so, specifically regarding situations where both IPv4 and IPv6 resolution is available for the same hostname (which used to cause issues and was supposed to have been fixed by these changes).

It's a long shot, given that it apparently works w/o `-P`, but might still narrow down exactly where things are breaking. I can't think offhand how parallel mode would affect resolution/connection in any interesting way :(

**Comment by anjos** [comment]
Ok, I was on the wrong direction. The problem seems to be related to the interaction between paramiko and the ssh-agent on a Debian distribution. After providing a key file to Fabric, all works OK and is **much** faster than ever!
