### ISSUE TITLE
Python3 support in Fabric 2

### ISSUE THREAD

**Issue by Daenyth** [fabric/fabric#1417]
I'd like to help get fabric working under python3. There appear to be many issues reported for python3 support, but they're all closed and comments are locked.

I don't see a branch on this repo for v2, so it's not clear how to get support.

What is left to be done?

**Comment by bitprophet** [comment]
Please see the roadmap - http://www.fabfile.org/roadmap.html - alpha for v2 out soon (really).

**Comment by Daenyth** [comment]
Is the best way to speed things up then to work on Invoke?

**Comment by ze-phyr-us** [comment]
@bitprophet I am reading through all these Python 3 issues and it's really frustrating to see nothing but links to the roadmap (with no ETAs), locked issues, and promises of v2 alpha "really soon". For example, in https://github.com/fabric/fabric/issues/1050#issuecomment-140577614 you say it would be out by the end of September 2015.

I get that this is an open-source project that you work on in your spare unpaid time. I get that delays happen. What I don't get is why there is such lack of transparency about v2. Why is it kept off GitHub, and why do you ignore offers of help? There are many people like @Daenyth that expressed interest in testing v2 and helping with Python 3 support. Why keep us all in the dark?

**Comment by nicktimko** [comment]
@ze-phyr-us here's a straightfoward Python 3 (supports 2.7 as well, so has effectively replaced mainline Fabric for me) port: https://github.com/mathiasertl/fabric/ (`pip install fabric3`) 

Fabric is pulling a Netscape, IMHO, favoring purity over practicality. Imagine if Python stopped (public?) development after 2.5 and didn't release (the meh) Python 3.0 until a couple years later because any interim improvements to the 2.x series were somehow "unclean".
