### ISSUE TITLE
Timeout isn't respected on slow SSH connection setup

### ISSUE THREAD

**Issue by DamianZaremba** [fabric/fabric#1422]
I have a number of servers that have a broken DNS configuration and UseDNS enabled within SSH.

This has the effect that the SSH banner is not presented until DNS has fully timed out, causing very slow SSH connection setups. The hang between the connection being established and the SSH banner being presented is in the order of ~15 seconds.

Setting env.timeout globally to 300 seconds in a fabfile, does not alter the banner_timeout of Paramiko, which has the effect of the connections failing due to a timeout as the banner is not presented in time, even though the timeout in Fabric is significantly longer.

Altering the client.connect call on line 449 of fabric/network.py to including the banner_timeout option (set to env.timeout) resolves the issue and connections do not time out as expected.

I'm not sure of the other side effects caused by doing this (e.g. if Paramiko counts the timeout value from after the banner is present, it effectively doubles the timeout - not very clear behaviour!), so perhaps another env. option would be a better choice.

If you have a preferred way of enabling this option to be set, I'm happy to code up a pull request.

**Comment by bitprophet** [comment]
Banner timeout is a semi recently added feature at the Paramiko level, which explains both why Fabric lacks a passthrough for it (tho see #1347) and why Paramiko itself may not be adding the two timeouts together correctly. Thanks for the input!

What I think needs doing:

* Search the Paramiko tracker for existing PRs/issues related to the disjoined timeout functionality
* If there aren't any, make one there, detailing current behavior & what the probable least-surprising behavior should be (I'd guess your assumption is accurate, that the general connect timeout should function as a default value for the banner timeout if not given; what should happen if both are set to non-empty values, may take more thought).
* We might actually want to just close this ticket here after that, since #1347 exists to solve the other problem.

**Comment by kaaveland** [comment]
Is this maybe solved in https://github.com/fabric/fabric/pull/1347 ?

**Comment by bitprophet** [comment]
Let's assume this is covered under either #1347 or #1475.
