### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Grazfather** [fabric/fabric#1424]
Are there plans to get fabric working on python3? Paramiko already supports python3, so you're the last step on the chain.

**Comment by kaaveland** [comment]
Yes, there are plans, there's a fabric 2 that aims to do this (amongst other things). See http://www.fabfile.org/roadmap.html. Paramiko, fabric and invoke are all maintained by the same person, so everything can't happen all at once, unfortunately.

**Comment by nicktimko** [comment]
For a drop-in replacement use `pip install fabric3` that comes from [this fork](https://github.com/mathiasertl/fabric/).

Despite being a relatively straightforward port, Fabric management refuses to make 1.x compatible with Python 3 while simultaneously keeping Fabric 2.x (which claims Python 3.x compatibility), private. Perhaps there is an absolute requirement to maintain compatibility with Python 2.5 (last patched in 2011), because `except Error, e` doesn't work in 3.x and `except Error as e` doesn't work before 2.6.

**Comment by Grazfather** [comment]
Thanks both of you! I will start using the fork. Feel free to close this issue.

**Comment by ashwin31** [comment]
Is this being worked out to give python3 support?
