### ISSUE TITLE
Exclude not working (as expected)

### ISSUE THREAD

**Issue by tino** [fabric/fabric#1534]
I have a task:
```
@hosts(['gorilla', 'macaque', 'baboon'])
@task
def deploy(**kwargs):
    ...
```

that I run as follows:
```
⌘ fab -x macaque,gorilla deploy
[gorilla] Executing task 'deploy'
[gorilla] run: ...
```

wut? I wanted gorilla excluded 🤔

Reading the execution model, I understand that decorators are high in the order of precedence for setting the `env.hosts` list, so I can't run `fab -H baboon deploy`. However, under [Excluding specific hosts](http://docs.fabfile.org/en/1.12/usage/execution.html#excluding-specific-hosts) it says:

> Note
> Using this option does not modify env.hosts – it only causes the main execution loop to skip the requested hosts.

So I would expect the the hosts I `-x`ed to be excluded. Is that wrong to expect? How would I accomplish this scenario?

Versions:
- Python 2.7.11 (default, Mar 16 2016, 10:27:53)
- Fabric 1.12.1
- Paramiko 1.17.2

**Comment by UkuLoskit** [comment]
Is this really a bug? According to the documentation it appears to be working as intended:

http://docs.fabfile.org/en/1.12/usage/execution.html#combining-exclusions

> For example, a global -x option will not affect a per-task host list set with a decorator or keyword argument, nor will per-task exclude_hosts keyword arguments affect a global -H list.

Since the `deploy` task has a task-specific host list, `-x` will have no effect on it.

The behavior you are looking for can be achieved like this:
`fab deploy:exclude_hosts=macaque;gorilla`

**Comment by bitprophet** [comment]
@UkuLoskit has it (thanks!) - the order of precedence for this stuff can be a little unintuitive sometimes, sorry :(

**Comment by tino** [comment]
Ah oke. Thanks
