### ISSUE TITLE
print message issues in fabric

### ISSUE THREAD

**Issue by daiyueweng** [fabric/fabric#1535]
Hi, I am using `Fabric3 1.12.post1` on `Win10 X64`. I tried the following program,

`def platform_user():`
    `print('Platform: ' + local('echo %OS%'))`
   ` print('Username: ' + local('echo %USERNAME%'))`    

the output is,
`[localhost] local: echo %OS%`
`Windows_NT`
`Platform:`
`[localhost] local: echo %USERNAME%`
`my_user_name`
`Username:`

`Done.`

'Platform' and 'Username' did not line up with the outputs, so how to fix this issue?

Cheers

**Comment by bitprophet** [comment]
Unfortunately, `local` doesn't get the line-by-line output prefix that `run`/`sudo` get, since it's just wrapping `subprocess` in the stdlib. (2.0 has a much-reworked set of runners that make this less of an issue, FWIW.)

I'd suggest either setting `env.output_prefix = False` to turn off the `[localhost] ` bit, or doing `local(..., capture=True)` and then manually printing the result, doing your own `splitlines` + prefix insertion, if you really want the prefix here. Good luck!
