### ISSUE TITLE
Document env.output_prefix

### ISSUE THREAD

**Issue by jphalip** [fabric/fabric#1538]
It is possible to hide all output prefixes by setting `env.output_prefix=False`, but this feature currently isn't documented. Could/should this be documented, and if so, where? (I'd say, presumably on the "Managing outputs" page.)

**Comment by bitprophet** [comment]
Originally the idea was to not document because it was just a partway solution.

Of course, that idea is now many years old and fab 1.x is close to feature-frozen, so...yea. It's permanent.

I'd merge a PR, I do think the Managing Outputs page is the right place to note it (as well as the page describing all `env` vars).

**Comment by jphalip** [comment]
Ok thank you. I've created https://github.com/fabric/fabric/pull/1539
As far as I could look up, I think this feature was added in 1.0.0. If that's incorrect let me know and I'll modify the commit.

**Comment by bitprophet** [comment]
That's close enough (the verisonadded). Let's roll this discussion into the PR :)
