### ISSUE TITLE
how does one structure/organize python fabric tasks to be more modular? 

### ISSUE THREAD

**Issue by rlam3** [fabric/fabric#1552]
how does one structure/organize python fabric tasks to be more modular? 

I’d like to seperate service tasks into different .py files within a fabfile directory. Thanks! 

I read that we can use a fabfile/ directory. however when tried... the tasks were not able to be found....

```bash
--myApp
`-- fabfile 
    |-- __init__.py
    |-- __init__.pyc
    `-- fab_tasks.py
```

When I do fab list... it doesn't find any of my tasks..

Would definitely love to get more example/tutorials as documentation on this. Thanks!

**Comment by bitprophet** [comment]
This is a general Python package/import issue - I'm guessing your `__init__.py` is empty? When code (like Fabric) does `import fabfile`, it just gets `fabfile/__init__.py`. `__init__.py` is thus responsible for importing the other modules in the package, so that they're visible.

So you probably just need to do something like `from .fab_tasks import task1, task2` in `__init__.py`. What, specifically, you import is up to you - some folks like to just `from .submodule import *` for each submodule so Fabric sees every single task; others like to filter a bit and only expose the most important tasks.

**Comment by rlam3** [comment]
To those who are searching for a way to better manage your fabfile.. 

https://github.com/chrisgo/fabric-example

**Comment by jabhishek87** [comment]
https://stackoverflow.com/questions/22351768/organizing-fabric-tasks-in-python-modules
