### ISSUE TITLE
files.append() duplicates lines when use_sudo=True is used

### ISSUE THREAD

**Issue by Suor** [fabric/fabric#1613]
Unless `shell=True` is used.

**Comment by ploxiln** [comment]
If I test the simplest case and the latest fabric, `append()` does not duplicate lines:

```
$ fab --version
Fabric 1.13.2
Paramiko 2.1.2
$ cat fabfile.py
from fabric.api import env, task, run
from fabric.contrib import files

@task
def test():
    files.append("/tmp/test.txt", "asdf", use_sudo=True)
    files.append("/tmp/test.txt", "asdf", use_sudo=True)
```

So, which version of fabric are you using, and what line content are you trying to append?

**Comment by Suor** [comment]
Same fabric/paramiko versions. Code is:
```python
    files.append('/etc/hosts', ['127.0.0.1 db', '127.0.0.1 redis'], use_sudo=True)
```

**Comment by ploxiln** [comment]
Hmm, works for me.

```
@task
def test():
    files.append('/tmp/test.txt', ['127.0.0.1 db', '127.0.0.1 redis'], use_sudo=True)
    files.append('/tmp/test.txt', ['127.0.0.1 db', '127.0.0.1 redis'], use_sudo=True)
```

```
$ cat /tmp/test.txt 
asdf
127.0.0.1 db
127.0.0.1 redis
```

Maybe your ssh remote user login shell is different? Mine is `/bin/bash`. (Even if you use `shell=False`, ssh forces commands to run under the login shell. If you use shell=True, fabric runs `env.shell` inside the login shell, and inside that the desired command.)

**Comment by Suor** [comment]
Reduced my `fabfile.py` to:
```python
from fabric.api import *
from fabric.contrib import files

env.cwd = '/home/ubuntu/app'
env.use_ssh_config = True
env.hosts = ['sclone']

@task
def test():
    files.append('hosts', ['127.0.0.1 db', '127.0.0.1 redis'], use_sudo=True)
```
Looks like setting `env.cwd` breaks things.

**Comment by ploxiln** [comment]
Yup that's it - `env.cwd` plus `sudo(... shell=False)` is a bad combination. These contrib.files functions often use `settings(hide('everything'))` which prevents the real error message from coming out, which might be something like "sudo: cd: command not found", and any error return code is interpreted as "egrep didn't find it".

**Comment by ploxiln** [comment]
Found previous issue #703 says this is fixed by letting you specify `shell=True`. I didn't know what that was useful for, now I do...

**Comment by Suor** [comment]
This is counterintuitive.

**Comment by ploxiln** [comment]
I agree.

The reason this is in "contrib" is because it's not "vigorously" "supported". It might be convenient for you, or it might not do what you need. You can roll your own help function that does exactly what you need with the core primitives `run()`, `sudo()`, `get()` and `put()`. Part of the problem with these contrib functions is that a lot of conveniences were added for different use cases and OSes, and are not very maintainable.

Anyway - I think the concern was that `shell=True` affected the escaping and quoting and sometimes made what people were already doing not work. So it was turned into another explicit option, which is only fully explained for [sed()](http://docs.fabfile.org/en/1.13/api/contrib/files.html#fabric.contrib.files.sed)).

I changed the escaping code in #1559 so the effect of `shell=True` would have to be re-investigated. You could also argue that if `use_sudo and env.cwd` then nothing useful happens for `shell=False` anyway, so it should just be enabled for that case even if it might not work right. But again, this is "contrib", so this is a low priority for the project.
