### ISSUE TITLE
Custom ssh_config_path with ProxyCommand configuration affected by a paramiko bug

### ISSUE THREAD

**Issue by avoidik** [fabric/fabric#1632]
Hi,

Custom ssh_config_path with ProxyCommand configuration affected by a paramiko bug. Approach with env.gateway works fine.

https://github.com/paramiko/paramiko/pull/962

**Comment by avoidik** [comment]
Problem is that paramiko trying to kill process which is already killed by itself after completion

Tested proposed PR and problem has gone away.

**Comment by bitprophet** [comment]
Hm, not sure this needs to be a ticket here? It's pretty much purely a Paramiko-level bug, on the Fabric end it's simply "are you using an SSH config with ProxyCommand in it", but once it's fixed in Paramiko, there's no action to take in this repo.

That said, now it's here for search reasons, so thanks! (And I think I saw you linking paramiko-962 in other tickets too, so thank you for that also!)

**Comment by avoidik** [comment]
It's here because Fabric produces two ugly unhandled exceptions (aprox. 30 lines of stderr log) after successful completion of it's job. Thanks for feedback
