### ISSUE TITLE
Test suite interacts with user's SSH config

### ISSUE THREAD

**Issue by rpkilby** [fabric/fabric#1638]
This might just be a wontfix, but my local username differs from the username I generally SSH with (bagel and rpkilby respectively). Since this is the case 99% of the time, I have this pasted at the top of my ssh config:

```
Host *
    User rpkilby
```

The test suite assumes that these usernames will match, and fails accordingly. A workaround is to either comment the block out, or to exclude all of the test hostnames.

```
Host * !host !myhost !justhost !meh
    User rpkilby
```

**Comment by bitprophet** [comment]
This is also an issue for Invoke (and potentially Paramiko as well.) Only real way to solve it is to make it easy to disable (less so for Fabric 1, but feasible in Invoke/Fab 2) and find some least-boilerplate way of smearing it on the entire test suite (this is the hard part, since it means behavior under test no longer quite resembles "real" behavior. It's doable but annoying, which is why it's not been a high priority.)

**Comment by bitprophet** [comment]
I think it is kind of a wontfix for now, for that reason. Thanks though!
