### ISSUE TITLE
v2 put/get don't perform tilde homedir expansion

### ISSUE THREAD

**Issue by pint12** [fabric/fabric#1653]
i have set
 `remote= '~/temp' `
put api translated it to `'/home/user/~/temp'` 
that caused the process to fail .

**Comment by bitprophet** [comment]
Thanks for the report! I probably haven't gotten around to porting the remote equivalent of `os.path.expanduser` from v1. Just looked and yup, it's very basic right now. Made myself a todo.

**Comment by bitprophet** [comment]
I recall one reason this wasn't done yet is it entails running shell commands in the background, which can rarely (but frustratingly) cause unexpected issues – imagine a user accidentally misconfiguring something related to command execution (or the remote server having some issue along the same lines) and then having shell exec errors bubble up from what they thought was a "simple" file transfer.

However given we had to implement it that way in v1, I assume there's no standard way of having the SFTP server perform expansion on our behalf, so we may be stuck doing the same thing here. Gonna double check first tho.

If we _do_ have to go that road I wonder if there are any ways to make it cleaner...for example having an opt-in `expand_tildes` kwarg or something, so that users have to understand they are turning additional behavior on. I don't really like that idea – it's a lot of friction for a very common necessity – but it still occurred to me.

Possibly best is to "amend" any exceptions that bubble up from the expansion step to make it clear they happened internally; or at least, to add very strict tests that ensure we always get a clear traceback so the user or a maintainer will see "ah yes, this is the internal tilde expansion – try running a regular command first to see what's going wrong"?

**Comment by bitprophet** [comment]
Only devil's advocate reason I can think of for going through with tilde expansion is compatibility with local file paths (i.e. the "run a nontrivial task against localhost w/o actually using SSH" use case, #98). In that sense, local code is much more likely to be incidentally chdir'd someplace outside `$HOME` and thus benefits from `~/xxx`.

But this seems pretty specious to me.

**Comment by bitprophet** [comment]
Went with "just update the docs informing users to use relative paths only".

Should somebody come along with an amazing reason why I'm an idiot (meaning both a use case _requiring_ tildes instead of relative paths, _and_ a method of performing expansion which is lightweight enough to be worth using) we can always revisit.

**Comment by bitprophet** [comment]
@pint12 to be super clear so you don't have to read all the above: please try simply using `temp/` instead of `~/temp/`, if you hadn't already. Should work fine!
