### ISSUE TITLE
local() does not set $SHELL

### ISSUE THREAD

**Issue by joshourisman** [fabric/fabric#1661]
Currently, if you wrap a command with the prefix context manager it executes using /bin/sh, but does not update the $SHELL environment variable accordingly. This becomes an issue if the context manager is wrapping a command that attempts to auto-detect the shell it's running in and alter behavior accordingly.

As a specific example, I have the following code in my fabfile:
```python
    with prefix('eval $(minikube docker-env)'), lcd(PROJECT_ROOT):
        docker_command = 'docker build -t {} {}'.format(local_image, service)
```

The `minikube docker-env` command attempts to detect your shell, and provides the necessary env variables for docker to use minikube (`eval` is obviously used to actually set those variables). Most of the time (for sh, bash, zsh, &c.), the shell detection is irrelevant as they all use the same `export` syntax to do this. However, fish does not, and if the fish shell is detected, the output will use `set -gx …` which simply doesn't work in sh (which prefix uses), causing the task to fail. As a result, if you're using fish and attempt to run that task, it won't work. (As it happens, all that's necessary is to change it to `minikube docker-env --shell=sh`, but there may be other circumstances in which there isn't such a simple option.)

To illustrate the issue, here's a contrived task that simply shows that even though the prefixed command is running in sh, the $SHELL env variable states that it's running in fish:

```python
@task
def test():
    with prefix('cd'):
        local('echo $SHELL')
```

The output of this task is:
```shell
$ fish
Welcome to fish, the friendly interactive shell
$ fab test                                                            
[localhost] local: echo $SHELL                                                                            
/usr/local/bin/fish                                                                                       

Done.   
```

**Comment by ploxiln** [comment]
I think this is actually due to `local()` and how shells work, and not due to `prefix()`.

Try this: `bash -l -c 'echo $SHELL'`  - for you I expect it will output "/usr/local/bin/fish". A sub-shell only changes the SHELL variable if it is not set at all, i.e. if you do `unset SHELL ; bash -l -c 'echo $SHELL'` the output should be "/bin/bash".

`local()` does not directly choose the shell, by default it just lets `Popen` use its default "/bin/sh", but `local()` allows to override it. So this will probably work for you: `local(docker_command, shell="fish")`.

Notice that you will have this problem with anything that uses python standard `subprocess.Popen(... shell=True)`, it's not really specific to Fabric.

Maybe a reasonable fix is for `local()` to specify `env` to be a copy of the current environment vars, but with SHELL removed.

**Comment by ploxiln** [comment]
Side note: if you read the first three paragraphs of https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html you'll see that good old GNU make has the same behavior as python subprocess.Popen() regarding SHELL

**Comment by joshourisman** [comment]
After doing some digging and starting work on a PR, I realized that as
well. One option I’ve come up with is to set SHELL to /bin/sh if shell
isn’t passed to `local()` otherwise to the value passed. Alternatively,
maybe something like adding `SHELL=$0` to the command prefix. Still playing
around with it.

This is probably a pretty uncommon edge case, but it seems like something
that should be avoidable.

**Comment by ploxiln** [comment]
a more portable temporary workaround I came up with:

```python
import os
if 'SHELL' in os.environ:
    del os.environ['SHELL']
```

**Comment by joshourisman** [comment]
Given the intention of SHELL not being set in the environment because it's meant to specify the choice of shell to use, it actually seems to make sense to explicitly set it to /bin/sh (or whatever the user specified). Certainly more Pythonic! 😁

**Comment by bitprophet** [comment]
Think I'm OK with the overall approach outlined in #1662 so let's roll into there.
