### ISSUE TITLE
Cut alpha/beta releases of fabric2 to pypi?

### ISSUE THREAD

**Issue by tony** [fabric/fabric#1672]
source: http://bitprophet.org/blog/2017/04/17/fabric-2-alpha-beta/

> It’s not on PyPI yet; no 2.x releases exist at time of writing. To obtain Fabric 2, you’ll need to do one of:

It makes it significantly easier to adopt/convert stuff like fabtools to fabric2 if a package is updated.

I also am aware from the post you'd like to keep the feedback under control, but I still think a pypi package being available is the best way to start getting people moved over.

**Comment by Aiky30** [comment]
I would agree with Tony here and would add that there could be many who would not know how to install a package from a repository and would rely on pip. On the flip side though, I guess this then also opens an avenue of users who may not be that Python savvy and could waste a lot of time on issues that are just inexperience / not actually issues but more support.

**Comment by bitprophet** [comment]
I hear & acknowledge the request (including Aiky's point, which is well made), but I'm still planning to wait for 2.0.0 to put it on PyPI.

One of the main reasons I'm avoiding PyPI is technical: last I checked, one cannot create a version number that PyPI/pip/friends will consider 'prerelease only' when its major version is also higher than the current stable release.

In other words, it looked like putting out e.g. `fabric-2.0.0a1` would show up as being "newer than" any `fabric-1.x.y.z`, despite being a prerelease-formatted version, and would thus pop up for `pip install fabric`, `pip install -U fabric`, etc.

----

I _could_ start using the `fabric2` namespace on PyPI to work around that first problem, but I made the decision a long time ago that I didn't want to go down that road officially, and I still think that's the right call. It's a not-uncommon practice to have a v1 as `foo` and a v2 as `foo2`, but it can create confusion as to what versions are available where, and more importantly, I want to put out non-rewrite 3.0, 4.0 etc in the less-distant future, and using `fabric3`, `fabric4` etc would just get silly. (Plus somebody else already owns `fabric3`...)

Additionally: if folks started using `fabric2`, they'll begin relying on it / expecting it to get _stable_ releases after 2.0.0, which creates more work for me (having to upload to both endpoints every time; easy to goof up and have them be out of sync; etc) and is just confusing (folks not knowing offhand which "channel" is getting which releases, etc.)

----

Finally - it's nearing the end of 2017 and I made myself a promise to put out 2.0.0 before 2018, because, jeez. I'm going to scale back work on other projects so I can get that done; it won't be a 100% feature-complete match for 1.x but it'll be quite usable regardless.

**Comment by tony** [comment]
However you want to do it. FYI [spacy](https://spacy.io) has alpha 2.0 releases on pypi and some things are broke. The blog post made it sound like it was useable right now.

> despite being a prerelease-formatted version, and would thus pop up for pip install fabric, pip install -U fabric, etc.

This really has felt like a gray area to me because I was never sure 100% how pip treated prereleases.

https://packaging.python.org/tutorials/distributing-packages/#pre-release-versioning

According to here: "pip and other modern Python package installers ignore pre-releases by default when deciding which versions of dependencies to install."

In any event, if fabric 2 *is* stable enough to start porting stuff over, then I'm more interested in seeing if pre-releases *could* work. If fabric 2 still needs more time, it's not as urgent.

I'm just excited. fabric is the only library left keeping me from 100% python 3.

**Comment by rpkilby** [comment]
Not voicing an opinion on the matter, but Django's alpha releases do not automatically install when using pip's `--upgrade` option. To install the pre-release/alpha, you would have to use the `--pre` option.
