### ISSUE TITLE
c.put confusion about string vs file-like object in local

### ISSUE THREAD

**Issue by peteruhnak** [fabric/fabric#1749]
According to [transfer.put() docs](http://docs.fabfile.org/en/2.0/api/transfer.html#fabric.transfer.Transfer.put), I should be able to either provide local path to a file (as a string), or a file-like object.

When using the former (string), I can specify in the `remote` path only the target directory. This is used in some [examples](http://docs.fabfile.org/en/2.0/getting-started.html?highlight=put#multiple-actions):

```py
c.put('myfiles.tgz', '/opt/mydata')
```

But when I try to do the same ( `c.put('file.txt', '/home/me/dir')`, I always end up with `IOError: Failure`, because it is actually behaving as if the `local` path was a file-like object and not a string.

It fails specifically on `paramiko.transport.sftp.sftp._log: [chan 0] open('/home/me/dir', 'wb')`

The solution is to always provide the full path, e.g.

```py
c.put('file.txt', '/home/me/dir/file.txt')
```

But that is inconsistent with the docs and examples.

Finally, having to provide the full path to `$HOME` is less than ideal, but there seems to be issue for that already #1653 

* Tested in Windows 10
* Fabric 2.0.0
* Paramiko 2.4.1
* Invoke 1.0.0

**Comment by bitprophet** [comment]
Sounds like a legit bug, will take a look later. Patches (and tests! since ours all pass :( implying we're missing some...) welcome.

**Comment by bitprophet** [comment]
OK, nope, all the munging is around empty or relative remote paths, there's no is-directory check.

**Comment by bitprophet** [comment]
While I'm in here, wondering how to handle FLOs too, in the case where remote path is a directory.

In v1, we looked at FLOs' `.name` attribute because that's [part of the Python FLO API](https://docs.python.org/2.7/library/stdtypes.html#file.name)..._but_ apparently only for debug log purposes (in #699). Whoops. I looked over our and Paramiko's code and don't see anything actually using that as a "filename" clue.

Anyway, so here in v2 we have the opportunity to address that for reals, or to just throw an explicit exception saying "whoa hey you need to give a non-directory remote file path for these". Probably both, since not all FLOs necessarily have the name attribute anyways.

**Comment by bitprophet** [comment]
OK, that's all fixed up, will be out in next bugfix release 🎉
