### ISSUE TITLE
In fabric  2.0.1 connection.get() fails in windows with PermissionError: [Errno 13] Permission denied:  when trying to copy to a custom local path.

### ISSUE THREAD

**Issue by nagavnaga** [fabric/fabric#1782]
`with Connection(host) as cxn:
    cxn.run(cmd)
    local_path = r'C:\Program Files\JetBrains\my codes\fabric framework\fabric2.0\SG_info'
    cxn.get(filename, local_path)`

Same is working fine when i leave the local path to default 
or 
Set the local path by changing the cwd() like below  and leave the local path to default. 

# os.chdir(r'C:\Program Files\JetBrains\my codes\fabric framework\fabric2.0\SG_info')

Full trace is below 
"C:/Program Files/JetBrains/my codes/fabric framework/fabric2.0/just1.py"
Traceback (most recent call last):
  File "C:/Program Files/JetBrains/my codes/fabric framework/fabric2.0/just1.py", line 14, in <module>
    cxn.get('sym.txt', local_path)
  File "C:\Users\venkan5\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fabric\connection.py", line 628, in get
    return Transfer(self).get(*args, **kwargs)
  File "C:\Users\venkan5\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fabric\transfer.py", line 112, in get
    sftp.get(remotepath=remote, localpath=local)
  File "C:\Users\venkan5\AppData\Local\Programs\Python\Python36-32\lib\site-packages\paramiko\sftp_client.py", line 769, in get
    with open(localpath, 'wb') as fl:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\JetBrains\\my codes'

**Comment by bitprophet** [comment]
Suspect this is the same bug as #1749, please follow there and give it another shot once that's fixed and out. Thanks!

**Comment by zachbryant** [comment]
I've been getting a similar issue with 2.2.1 too. As it turns out, the sftp server and ssh server of the same machine don't always display the same directory structures. I was getting permission denied or file not found because I was stuck in a different root folder. Unfortunately I found that this is not always the case, as one of my servers does have the same sftp and ssh directory structures.

I found that working directly with connection.sftp(), connection.command_cwds, and opening local files as bytes solves my problems.
