### ISSUE TITLE
ctx.local not exists while run without -H flag, this seems very confuse.

### ISSUE THREAD

**Issue by hackrole** [fabric/fabric#1793]
```python
from invoke import task

@task
def hello(ctx):
    ctx.local("uname -a")
```
if I run it with
```shell
fab hello
```
it will output errors for local not exists.

while I run it with
```shell
fab -H name@host hello
```
it works.

so It seems I have to write different code for local and no-local, this seems not good. 
Did I missing something or is there any design choices behind this?

**Comment by bitprophet** [comment]
This a deliberate design choice due to local-only code living in its own lower level library (where calling it `local` would _also_ be confusing!) It was the least-bad option open to us. If there's a spot in our docs that a 'warning' or 'note' block could have prevented you from getting confused, please let us know!
