### ISSUE TITLE
conn.local() doesn't inherit envvars (including SSH_AGENT)

### ISSUE THREAD

**Issue by ChaoticMind** [fabric/fabric#1801]
`conn.local()` and invoke's `invoke.run()` have different contexts:

I get different behavior if I run a command with `c.local(cmd)` vs `from invoke import run as local` then `local(cmd)`.

The easiest way to visualize it is for cmd to be `printenv`. In other words, the following two fabfiles have differing behavior:

```python
from invoke import task


@task
def test(c):
    c.local('printenv')

```

Which can be run via `fab -H 8.8.8.8 test`

And:
```python
from invoke import task
from invoke import run as local


@task
def test(c):
    local('printenv')

```
Which can be run via `fab -H 8.8.8.8 test`

Practically, this means that the `ssh-agent` is not available when I call `c.local()`, which means commands like `c.local(git push origin master)` will fail with `Permission denied (publickey)`.

It's not clear to me if this is known behavior, related to #1637. If so, the workaround described in this issue may prove useful for now.

**Comment by rpkilby** [comment]
[`invoke.run`](https://github.com/pyinvoke/invoke/blob/master/invoke/__init__.py#L24-L40) has an anonymous context, which is naturally different from the connection conte

**Comment by rpkilby** [comment]
This is expected behavior. [`invoke.run`](https://github.com/pyinvoke/invoke/blob/master/invoke/__init__.py#L24-L40) uses an anonymous context, which is naturally different from the connection/context passed to your task.

#1637 is a separate issue, which is that `conn.run()` and `conn.local()` share the same context. As a result, both commands are affected by `cd` and `prefix`, which is generally not be the desired result.

**Comment by ChaoticMind** [comment]
Got it, makes sense.
However, it's still true that `conn.local()`doesn't inherit the appropriate environment variables that make the SSH agent work. I think this is unexpected behavior.

I'm changing the title of this issue to better reflect that.

**Comment by bitprophet** [comment]
That's actually still due to the issues you and @rpkilby linked - the tl;dr is that right now `local` is inheriting a single shared set of config variables which was intended only for `run`. One of those is `replace_env`, which controls whether or not the subprocess inherits the running process' shell env. It defaults to off in `run` because security. Once we fix this so they pull from different config locations, we'll make sure that `local` goes back to behaving identically to Invoke's `run`.

**Comment by bitprophet** [comment]
Sorry, the "main" tracking ticket for the issue is #1752, so follow that, it'll track the issue whether or not we use part or all of Ryan's PR(s). Sorry for the confusion, ticketing is hard 🙃
