### ISSUE TITLE
.zshrc or .bashrc not being sourced

### ISSUE THREAD

**Issue by chadgh** [fabric/fabric#1816]
I have a simple `fabfile.py` as follows:
```python
from invoke import task

@task
def versions(c):
    c.run('pyenv versions')
```
And a `fabric.yml` file:
```yaml
run:
  shell: "/usr/bin/zsh"
```
Running `fab versions` or `fab -H prod versions` results in the following:
```
zsh:1: command not found: pyenv
```
If I change the `c.run` line as follows:
```python
c.run('source ~/.zshrc && pyenv versions')
```
I get the expected list of available versions from `pyenv` output.

**Is there a better way to assure that my `.zshrc` file will be executed for each connection?**

**Comment by bitprophet** [comment]
The generically best way to handle this is to allow configuration of the shell program being executed, in terms of its flags - right now we (or the subprocess lib, or the sshd, depending) do `/path/to/shell -c command`. Making this into `/path/to/shell -i -c command` would (for zsh anyways) trigger interactive mode and loading of your zshrc. See the abovelinked issue reference for that feature-add ticket.

It's not clear to me at the moment how to make this work on the sshd end, since we presently just ask it to run the command; we do not have the ability to specify shell at all, outside of an internal shell wrapper (which is not currently planned as we've done that before, and it stinks.) So that's outstanding and something I'd like to look into further.

----

Speaking _specifically_ about zsh, you may just want to move your pyenv hook and similar into `~/.zshenv`, which will load in any and all zsh sessions regardless of interactivity. That's arguably the "correct" way to solve this and certainly is the fastest at the moment, especially if your remote login shell is also zsh.

**Comment by chadgh** [comment]
@bitprophet Thanks for the options. I've decided to make sure the pyenv setup is done in the `/etc/zshenv` file which solves other problems I've faced outside of fabric's usage. Doing that has solved my issues. Thanks again.
