### ISSUE TITLE
allow executing 'batch' commands for groups

### ISSUE THREAD

**Issue by ophiry** [fabric/fabric#1848]
this is mainly for SerialGroups
in may cases, I want to serially execute a set of commands on a group of remote servers
using SerialGroup will run each command on all servers, and then move to the next command.

I'm looking for a method to run all commands on the first server, end then move to the next server (like doing rolling deploys)

**Comment by jscott0918** [comment]
What is the point of using a group at that point? If Serial execution is preferred, and you want to complete execution of all tasks host-by-host, just using individual connection objects seems fairly manageable. If you don't want to refactor away from SerialGroups, you could just loop over the connections within the SerialGroup and run each batch that way.

**Comment by bitprophet** [comment]
This is definitely a thing we want to do; see #1594 or (maybe) #1691. Thanks!

**Comment by bitprophet** [comment]
@jscott0918 BTW - the case I see for SerialGroup here is more that one should write against Group-the-superclass, and can then drop in any implementation/exec-strategy subclass as needed; that way you can go from serial to threaded to coroutine to whatever.

You're not wrong that SerialGroup itself feels silly because it's just a slightly different syntax for a `for` loop, but it's a very convenient baseline/fallback implementation.

I'll admit that separating strategy (serial, parallel one task at a time, parallel N tasks at a time, etc) from nuts and bolts implementation (loop, thread, coroutine, greenlet, ???) is something that may need doing as well, but for now it seems likely both can be served within this class hierarchy "well enough" for now.
