### ISSUE TITLE
context.run vs connection.local

### ISSUE THREAD

**Issue by sam-dieck** [fabric/fabric#1858]
When running a task through the "fab" tool, if you supply a -H <host> argument, it'll pass a connection to the task, and if you don't, it'll pass a context to it. This brings some ambiguity when running local commands due to different method names (`context.run` vs `connection.local`).

If I have a task that only executes local commands, it'll look something like this:
```
@task
def mytask(c):
  c.local('mycomand')
```

This only works if I specify a host argument because connection implements "local", if I don't specify a host, this task fails because c would be of type "context", which doesn't implement "local".

What troubles me more is that for this task to work correctly,  I need to replace `c.local` for `c.run` (because thats what context implements), however, it becomes very confusing and ambiguous what the task is really trying to do... for example looking at this task:

```
@task
def mytask(c):
  c.run('mycomand')
```

I see the following problems with the above function:
* It's not clear if the function is meant to run local or remote commands
* If you run the task with a host parameter (or another task call's it passing a connection parameter), the task will run the command on the remote machine.
* If you run the task without a host parameter, it'll run the command locally.

The solution for me has been directly using `invoke.run` for local calls, but I don't know what other negative implications it has for not using the context. I feel like maybe a cleaner solution may be to implement `context.local` that will just call `context.run`. to make things more cleaner and clearer.

What do you guys think? Am I approaching this incorrectly?

Thanks
Sam

**Comment by rpkilby** [comment]
This seems related to #1755.

**Comment by bitprophet** [comment]
Yea it's tied into the #98 - #1637 - #1755 ticket complex, tho I don't think this specific angle (which boils down to "consider aliasing `invoke.context.Context.run` as `invoke.context.Context.local`") has been quite raised yet.

My instinct is that we don't want this because Invoke should be "pure" and not have strange looking warts that make no sense to Invoke-only users & only serve client codebases. This is one reason the code from #1755 / #1637 is still compelling (and why I need to find time to revisit it and make a ruling...E_NOTIME).

Let's close this as a duplicate and keep discussion in #1755 for the time being. Specifically I'm curious if @sam-dieck thinks the composition-based approach in that issue feels sensible from their perspective.

**Comment by sam-dieck** [comment]
@bitprophet I think it makes sense to close this as a duplicate. I also agree that invoke should be pure and we shouldn't be mixing it with `fab` needs, muy suggestion came out without really fully understanding/studying the whole fabric architecture.

Regarding my opinion of #1752, using composition+local_task in this case seems like a reasonable solution. However, I feel like the fundamental problem is the ambiguity that the `fab` tool introduces, and while we can fix it by introducing the `local_task` as suggested in #1752 , introducing another decorator will add some more complexity to the library, and now you would have multiple ways of achieving a same goal (either using `@local_task` + `context`, or using a `@task` + `connection.local`).

I don't know much about the fab/invoke architecture, but what if the fab tool ALWAYS passes a connection to the underlying task? even if no "host" was specified and the connection is invalid, that way, a fabric local task can choose to only use `conn.local` (either as a composite or an extension of context) without further complicating the writing of tasks with many different decorators and giving people different paths of achieving the same thing... 
At the end of the day, `fab` is the equivalente of `inv` , but for networked oriented tasks... shouldn't it always behave like so and return a connection even for local tasks?

Again, I havet fully studied fabric architecture, this is just an idea, let me know what you think.

Thanks
Sam

**Comment by rpkilby** [comment]
The idea with #1755 is that the Fabric's remote `task`s would *always* receive a `Connection`, even if no host was specified, and a `local_task` would always receive a `Context`, even if a host *is* specified. The task decorators would enforce receiving the correct type. e.g., a local task would complain if you sent a `Connection` to it.

**Comment by rpkilby** [comment]
Given #1755, my thoughts on handling #98 would be:
- There should be a `LocalConnection` (or a better name) that inherits `Connection`, but implements run/sudo/etc.. in an SSHless manner. The `.local` property would still refer to the invoke `Context`.
- Program exposes an option for SSHless local connections
- Executor obeys this option, creating a `LocalConnection` instead of a `Connection`
- The Fabric task decorator is happy, since the `LocalConnection` is a `Connection`
