### ISSUE TITLE
How to use/copy the environment of a login bash?

### ISSUE THREAD

**Issue by halloleo** [fabric/fabric#1871]
In Fabric when I issue a local pipenv command, it does not find the command. E.g.:

    @task
    def test(ctx):
        res = ctx.run('pipenv run sigal --help')

returns the error:

    Warning: the which -a system utility is required for Pipenv to find Python installations properly.
      Please install it.

However when I run

    @task
    def test2(ctx):
        res = ctx.run('bash -l -c "pipenv run sigal --help"')

it works. So I figure that the environment (particularly the PATH variable) is set differently. 

I think a general solution is be to use/copy the whole login environment to the `namespace` object on fabfile executing.

Is there an easy way to inject the environment from a `bash -l` shell call to the `namespace` object?

**Comment by bitprophet** [comment]
I just added an FAQ about this since it keeps coming up. The tl;dr is that Fabric 1 used to do exactly what you're doing by hand here, but manual shell wrapping like that has an enormous number of problems around quoting/escaping, so we dropped it in v2.

Unfortunately, this then leads to problems where it's harder to match your remote interactive shell config; the default invocation by an sshd is very non interactive, non login, which changes how most shells behave.

See http://www.fabfile.org/faq.html#the-remote-shell-environment-doesn-t-match-interactive-shells (again, brand new. Also not 100% tested.)

**Comment by bitprophet** [comment]
Also, to clarify something I found researching that FAQ - @halloleo can you share exactly which bash startup files you're using to set up pipenv? (`~/.bashrc` vs `~/.bash_profile` vs etc)

I'm curious whether the assertion in bash's manpage about "we'll load `~/.bashrc` when you run via ssh" is accurate or not.

**Comment by ploxiln** [comment]
it's pretty complicated: http://www.solipsys.co.uk/new/BashInitialisationFiles.html

**Comment by halloleo** [comment]
> @halloleo can you share exactly which bash startup files you're using to set up pipenv? (`~/.bashrc` vs `~/.bash_profile` vs etc)

I am using .bashrc. However my use case is a *local* pipenv! That's what I cannot get to work!

Both, the `sigal` command and the `fab` command are in this environment.

**Comment by halloleo** [comment]
> @halloleo can you share exactly which bash startup files you're using to set up pipenv? (`~/.bashrc` vs `~/.bash_profile` vs etc)

I am using .bashrc. However my use case is a *local* pipenv. That's what I cannot get to work!

Both, the `sigal` command and the `fab` command are in this environment.

**Comment by halloleo** [comment]
Well, I found a way:  I have to copy the env vars by hand like this:

    @task
    def test3(ctx):
        env={}
        for e in os.environ:
            env.update({e: os.environ.get(e)})

        res = ctx.run('pipenv run sigal --help', env=env)

But I think it shouldn't be needed to do so...
