### ISSUE TITLE
Confusing Connection's user documentation

### ISSUE THREAD

**Issue by revolter** [fabric/fabric#2105]
The documentation for the `user` parameter of the `Connection` class states that it defaults to `config.user`, but using

```py
config = Config(user=myuser)
```

fails with

```
TypeError: __init__() got an unexpected keyword argument 'user'
```

**Comment by tasosalvas** [comment]
```python
from fabric import Config, Connection

foo = Config(overrides = {'user': 'bar'})
foo.my_value = "It's just a dict with a few creature comforts."

sausages = Connection("baz", config=foo)

print(f"user: {sausages.user}")
print(f"Frankly: {sausages.my_value}")
```

**Comment by revolter** [comment]
Thanks, didn't think about that.

Do you know what is the preferred/correct way? Specify the user for a `Config` object, and then pass it to a `Connection` object, or specify is directly for a `Connection` object?

**Comment by tasosalvas** [comment]
Well, depends on who's reviewing the code, I guess :)

If you won't be reusing that `Config` or using the [configuration hierarchy](http://docs.pyinvoke.org/en/stable/concepts/configuration.html#the-configuration-hierarchy) to aggregate things from `fabric.yml` etc, there's little point in instantiating it independently.

If your `~/.ssh/config` is in order, so that `ssh myserver` just works, all you'd need is `Connection('myserver')` to get the ssh stuff populated correctly. Then you can just override `.user` in place for a dedicated app user or whatever.
