### ISSUE TITLE
What to do with the Connection object?

### ISSUE THREAD

**Issue by revolter** [fabric/fabric#2106]
Migrating to v2, I created a `Connection` object

```py
import configparser
import os

import fabric

fabfile_config = configparser.ConfigParser()

fabfile_config.read('fabfile.cfg')

fabric.Connection(
    host=fabfile_config.get('Fabric', 'Host'),
    user=fabfile_config.get('Fabric', 'User'),
    connect_kwargs={
        'key_filename': os.path.expanduser(fabfile_config.get('Fabric', 'KeyFilename'))
    }
)
```

but

```py
@fabric.task(help={'command': 'The shell command to execute on the server'})
def execute(context, command = None):
    if not command:
        return

    context.run(command)
```

is executing the `command` locally, instead of running it on the server.

Shouldn't the `context` parameter be my connection?

**Comment by revolter** [comment]
Also, the upgrading docs says that the first parameter "will be a fabric.connection.Connection object at runtime", but as I said, in my case, it's an `invoke.context.Context` object instead. Why is that?

**Comment by revolter** [comment]
I would have expected for a `connection` parameter to the `@task` decorator, similar to the `hosts` one.

**Comment by hiphamster** [comment]
@revolter Were you able to figure this out? I'm considering switching to fabric from invoke, but I ran into the same issue - without explicit connection object, task runs locally, which is really bad.

**Comment by revolter** [comment]
Somehow, yes. I _think_ that I was creating the connection object incorrectly. [Here](https://github.com/revolter/FileConvertBot/blob/master/fabfile.py) is the entire code that I use, let me know if there's something you don't understand.

**Comment by hiphamster** [comment]
@revolter Thanks for the reply. I'm pretty sure this will help.

**Comment by hiphamster** [comment]
@revolter I looked at your code, it appears you mostly do remote operations - most of your tasks take Connection instead of Context. In my case, i need to do run commands both locally and remotely. Also, i'd like to be use the '-R --dry' option, before i run the commands, as a sanity check. If i pass the connection instead of context, '-R' is ignored, and Connection.run() executes regardless.

**Comment by revolter** [comment]
Yeah, it's all very confusing. I wish I didn't start using this project, as it seems like it's not going anywhere too soon... And as you can see, I only need some pretty basic tasks, and yet I wasted countless hours on it.

**Comment by davidjmemmett** [comment]
> Yeah, it's all very confusing. I wish I didn't start using this project, as it seems like it's not going anywhere too soon... And as you can see, I only need some pretty basic tasks, and yet I wasted countless hours on it.

How very constructive. I've only just started helping out on this project, and this sort of feedback isn't going to encourage me (or probably anyone else) to try to help.

**Comment by revolter** [comment]
I know it's not constructive, but it's the reality. It has 46 opened pull request, most of them completely ignored, and the last commit is from the last year, with the message:

> Last ever LICENSE copyright update
> Just so it goes out on a cool looking year :D

which sound to me like this project is going to be abandoned.

If you really want to move this project forward, I think that the best bet would be for you to fork it.

**Comment by davidjmemmett** [comment]
Thanks for your feedback @revolter. If it makes you feel any better - there have been [389 commits](https://github.com/fabric/fabric/tree/2.6) to `2.6` since [the commit you referenced](https://github.com/fabric/fabric/commit/34edfe4a1cc9e3d72c3cc41490673db29afe7bbb), which FYI was marking the date in the LICENSE file for `2.0`, an older version of fabric which is no longer being actively developed.

We will change the default branch in GitHub at some point.

**Comment by davidjmemmett** [comment]
Reading through it, it appears that you have resolved this issue yourself. Please re-open if this is not the case.
