### ISSUE TITLE
getting remote mysql shell through python

### ISSUE THREAD

**Issue by thinksabin** [fabric/fabric#2128]
Hi,

Sorry this might not be the proper place to ask for a suggestion but I'm kinda lost going through the fabric2 connection documents.
I'm trying to get a remote machine's bash shell with python script and also the mysql shell of the remote machine. 

Getting the remote bash shell was straight forward with new api using Connection and 'run' method.
`def connect_bash():
    connect = Connection(host='192.168.0.16', user='hello', port=22, connect_kwargs={'password':'heylo'})
    myshell = connect.run("/bin/bash", pty=True)`

But I'm struggling to get the mysql shell from the remote machine. Currently I tried using local_forward but it only run the db command and won't give me the mysql shell. 

Is there a way I can achieve that using the fabric2 ?

Thank you.

**Comment by codingadvocate** [comment]
Shell and SQL protocols are quite different, as well as their security mechanisms... so perhaps a bit more explanation is in order?  Answering the following may help lay a foundation for folks to help:

1) Are you trying to connect via SQL to a remote database/instance/schema on a target database platform (running on host 192.168.0.16)?

2) Are you trying to connect via Shell (e.g. SSH) to a remote system (e.g. host 192.168.0.16), before attempting a local SQL connection?

3) Is Python installed (for available DB adapters) or other DB-specific CLI utilities or drivers, available for use - on the target system?

**Comment by thinksabin** [comment]
Thank for your kind reply @codingadvocate 

I am trying to connect via shell (ssh) to remote system with mysql database installed (192.168.0.16). The mysql listen at localhost: 3306 in remote machine and can not be directly accessible so I'm trying to write a python script that can give direct access to mysql shell in the remote machine through ssh (considering every credentials for ssh and mysql are hardcoded inside the script). I tried using local_forward but I guess it won't be able to give me mysql prompt.
eg: python remotemysql.py 
mysql>

The remote machine also has the mysql client installed along with similar python libraries for mysql connection.

**Comment by codingadvocate** [comment]
If I understand the scenario, you want to establish an SSH connection to a remote system and then query a local mysql database.  I can't see what's in your remotemysql.py script... it may need pipe redirects, or as you suggested - port forwarding.  

Can you put it all into a single inline command? Have you tried issuing something like this through fabric (if script.sql is on the remote system):  
> mysql database_name < script.sql

Or put the SQL statement on the fabric command.

I don't think it will work if you want to establish a long-standing SQL connection and issue commands into it.  I've only used Fabric/Paramiko to batch self-sufficient or all-inclusive commands to remote systems. 

If you can't package it up into something self-sufficient to issue across the Fabric SSH connection, you have other Python mechanisms to do this remotely.  For example, import mysql.connector, connect to the remote database, and do whatever you want to do.  Or use an ORM (my favorite is SqlAlchemy) if you have alot of DB interaction - especially favorable with queries across class/table inheritance structures.  However, a remote SQL connection means you may need to tweak firewalls and/or ACLs to allow the connection, since you said the remote machine is not directly accessible.  Just my 2 cents... I imagine other folks will have more to suggest.

**Comment by thinksabin** [comment]
Thanks a lot for sharing the ideas.
This has been ambitious scripting for me. I believe we can run batch of self-sufficient sql queries with local forward (have completely tested ). The long standing sql prompt might be very challenging from fabric ssh. 
I will keep exploring and will wait if other folks have more to suggest. Will definitelt share the work around if I find one. 

Thanks again.

**Comment by thinksabin** [comment]
hi,

I found out directly call the mysql binary will do.
`def connect_sql_shell():
    connect = Connection(host='192.168.0.16', user='sabin', port=22, connect_kwargs={'password': 'sabin'})
    myshell = connect.run("/usr/bin/mysql -u sabin -p", pty=True)`

this actually gave me what i wanted so far. 

Thanks.
