### ISSUE TITLE
Unable to connect through socks proxy with key_filename

### ISSUE THREAD

**Issue by sonoman** [fabric/fabric#873]
I have my fabfile setup to work with identity key_filename. but when I try to configure env.gateway to my socks 5 proxy, it asks for the password. I know that identity keyfile works because i tested that with ssh.

fabfile config

env.user = "ubuntu"
env.key_filename = "config/certs/cert.pem"
env.gateway = 'myproxyserver:1080'

this is what i'm getting:

[54.99.88.88] sudo: sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
No handlers could be found for logger "paramiko.transport"
[54.99.88.88] Login password for 'ubuntu': 

The IP address is the actual address to which I'm trying to reach, so I guess that socks proxy is working....but it seems like keyfile is not being sent....there is also an error in paramiki.transport that i don't know.

**Comment by kaaveland** [comment]
You can set `ProxyCommand nc -x myproxyserver:1080 %h %p` in your `~/.ssh/config` for that host and set `env.use_ssh_config = True` instead of setting `env.gateway`. Another option might be to not use `env.gateway` and try something like the monkey-patch solution from https://github.com/Anorov/PySocks

I believe that SOCKS unfortunately isn't a transparent proxy solution (`nc -x` means use SOCKS), and paramiko does not appear to understand SOCKS. If this was to be implemented in fabric, paramiko probably would need to understand SOCKS first. That seems like an idea for an improvement, but it also seems like a considerable task.

Maybe this should be closed -- this has been open for 2 years and it doesn't seem like anyone's interested in implementing it.

**Comment by bitprophet** [comment]
Yup, closing for timeout. Noting for record that Paramiko doesn't do SOCKS yet. I thought I saw a feature request for it but don't see one in my search `¯\_(ツ)_/¯` Someday!
